[theme]
inherit = "sphinx_wagtail_theme"
stylesheets = [
    "dist/theme.css",
]
sidebars = [
    "searchbox.html",
    "globaltoc.html",
]
pygments_style = { default = "none" }

[options]
project_name = "Sphinx Wagtail Theme"
searchbox_text = "Search notes"
logo = "img/wagtail-logo-circle.svg"
logo_alt = "Wagtail"
logo_height = "59"
logo_url = ""
logo_width = "45"
header_links = ""
footer_links = "Features|https://wagtail.org/features/, About Wagtail|https://wagtail.org/about-wagtail/, Services|https://wagtail.org/services/, Blog|https://wagtail.org/blog/, Packages|https://wagtail.org/packages/, Developers|https://wagtail.org/developers/"
github_url = "https://github.com/wagtail/sphinx_wagtail_theme/blob/main/docs/"
